// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Product;
@class Product_Builder;
@class Product_ProductReview;
@class Product_ProductReview_Builder;
typedef enum {
  Product_OrderStatusOrdered = 0,
  Product_OrderStatusShipped = 1,
  Product_OrderStatusIdle = 2,
} Product_OrderStatus;

BOOL Product_OrderStatusIsValidValue(Product_OrderStatus value);


@interface ShopRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Product : PBGeneratedMessage {
@private
  BOOL hasStarred_:1;
  BOOL hasId_:1;
  BOOL hasPrice_:1;
  BOOL hasName_:1;
  BOOL hasStatus_:1;
  BOOL starred_:1;
  int32_t id;
  int32_t price;
  NSString* name;
  Product_OrderStatus status;
  NSMutableArray* mutableReviewsList;
}
- (BOOL) hasName;
- (BOOL) hasId;
- (BOOL) hasPrice;
- (BOOL) hasStarred;
- (BOOL) hasStatus;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t id;
@property (readonly) int32_t price;
- (BOOL) starred;
@property (readonly) Product_OrderStatus status;
- (NSArray*) reviewsList;
- (Product_ProductReview*) reviewsAtIndex:(int32_t) index;

+ (Product*) defaultInstance;
- (Product*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Product_Builder*) builder;
+ (Product_Builder*) builder;
+ (Product_Builder*) builderWithPrototype:(Product*) prototype;

+ (Product*) parseFromData:(NSData*) data;
+ (Product*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Product*) parseFromInputStream:(NSInputStream*) input;
+ (Product*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Product_ProductReview : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasRating_:1;
  BOOL hasReviewer_:1;
  BOOL hasReview_:1;
  int32_t id;
  int32_t rating;
  NSString* reviewer;
  NSString* review;
}
- (BOOL) hasId;
- (BOOL) hasReviewer;
- (BOOL) hasReview;
- (BOOL) hasRating;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* reviewer;
@property (readonly, retain) NSString* review;
@property (readonly) int32_t rating;

+ (Product_ProductReview*) defaultInstance;
- (Product_ProductReview*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Product_ProductReview_Builder*) builder;
+ (Product_ProductReview_Builder*) builder;
+ (Product_ProductReview_Builder*) builderWithPrototype:(Product_ProductReview*) prototype;

+ (Product_ProductReview*) parseFromData:(NSData*) data;
+ (Product_ProductReview*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Product_ProductReview*) parseFromInputStream:(NSInputStream*) input;
+ (Product_ProductReview*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Product_ProductReview*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Product_ProductReview*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Product_ProductReview_Builder : PBGeneratedMessage_Builder {
@private
  Product_ProductReview* result;
}

- (Product_ProductReview*) defaultInstance;

- (Product_ProductReview_Builder*) clear;
- (Product_ProductReview_Builder*) clone;

- (Product_ProductReview*) build;
- (Product_ProductReview*) buildPartial;

- (Product_ProductReview_Builder*) mergeFrom:(Product_ProductReview*) other;
- (Product_ProductReview_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Product_ProductReview_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Product_ProductReview_Builder*) setId:(int32_t) value;
- (Product_ProductReview_Builder*) clearId;

- (BOOL) hasReviewer;
- (NSString*) reviewer;
- (Product_ProductReview_Builder*) setReviewer:(NSString*) value;
- (Product_ProductReview_Builder*) clearReviewer;

- (BOOL) hasReview;
- (NSString*) review;
- (Product_ProductReview_Builder*) setReview:(NSString*) value;
- (Product_ProductReview_Builder*) clearReview;

- (BOOL) hasRating;
- (int32_t) rating;
- (Product_ProductReview_Builder*) setRating:(int32_t) value;
- (Product_ProductReview_Builder*) clearRating;
@end

@interface Product_Builder : PBGeneratedMessage_Builder {
@private
  Product* result;
}

- (Product*) defaultInstance;

- (Product_Builder*) clear;
- (Product_Builder*) clone;

- (Product*) build;
- (Product*) buildPartial;

- (Product_Builder*) mergeFrom:(Product*) other;
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (Product_Builder*) setName:(NSString*) value;
- (Product_Builder*) clearName;

- (BOOL) hasId;
- (int32_t) id;
- (Product_Builder*) setId:(int32_t) value;
- (Product_Builder*) clearId;

- (BOOL) hasPrice;
- (int32_t) price;
- (Product_Builder*) setPrice:(int32_t) value;
- (Product_Builder*) clearPrice;

- (BOOL) hasStarred;
- (BOOL) starred;
- (Product_Builder*) setStarred:(BOOL) value;
- (Product_Builder*) clearStarred;

- (BOOL) hasStatus;
- (Product_OrderStatus) status;
- (Product_Builder*) setStatus:(Product_OrderStatus) value;
- (Product_Builder*) clearStatus;

- (NSArray*) reviewsList;
- (Product_ProductReview*) reviewsAtIndex:(int32_t) index;
- (Product_Builder*) replaceReviewsAtIndex:(int32_t) index with:(Product_ProductReview*) value;
- (Product_Builder*) addReviews:(Product_ProductReview*) value;
- (Product_Builder*) addAllReviews:(NSArray*) values;
- (Product_Builder*) clearReviewsList;
@end

