// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtoBuf.pb.h"

@implementation ProtoBufRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ProtoBufRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface CiklumOffice ()
@property (retain) NSString* name;
@property (retain) CiklumOffice_AddressGPB* address;
@property (retain) NSMutableArray* mutableEmployeesList;
@end

@implementation CiklumOffice

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasAddress {
  return !!hasAddress_;
}
- (void) setHasAddress:(BOOL) value {
  hasAddress_ = !!value;
}
@synthesize address;
@synthesize mutableEmployeesList;
- (void) dealloc {
  self.name = nil;
  self.address = nil;
  self.mutableEmployeesList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.name = @"";
    self.address = [CiklumOffice_AddressGPB defaultInstance];
  }
  return self;
}
static CiklumOffice* defaultCiklumOfficeInstance = nil;
+ (void) initialize {
  if (self == [CiklumOffice class]) {
    defaultCiklumOfficeInstance = [[CiklumOffice alloc] init];
  }
}
+ (CiklumOffice*) defaultInstance {
  return defaultCiklumOfficeInstance;
}
- (CiklumOffice*) defaultInstance {
  return defaultCiklumOfficeInstance;
}
- (NSArray*) employeesList {
  return mutableEmployeesList;
}
- (CiklumOffice_EmployeeGPB*) employeesAtIndex:(int32_t) index {
  id value = [mutableEmployeesList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasAddress) {
    return NO;
  }
  if (!self.address.isInitialized) {
    return NO;
  }
  for (CiklumOffice_EmployeeGPB* element in self.employeesList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasAddress) {
    [output writeMessage:2 value:self.address];
  }
  for (CiklumOffice_EmployeeGPB* element in self.employeesList) {
    [output writeMessage:3 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasName) {
    size += computeStringSize(1, self.name);
  }
  if (self.hasAddress) {
    size += computeMessageSize(2, self.address);
  }
  for (CiklumOffice_EmployeeGPB* element in self.employeesList) {
    size += computeMessageSize(3, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CiklumOffice*) parseFromData:(NSData*) data {
  return (CiklumOffice*)[[[CiklumOffice builder] mergeFromData:data] build];
}
+ (CiklumOffice*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice*)[[[CiklumOffice builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice*) parseFromInputStream:(NSInputStream*) input {
  return (CiklumOffice*)[[[CiklumOffice builder] mergeFromInputStream:input] build];
}
+ (CiklumOffice*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice*)[[[CiklumOffice builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CiklumOffice*)[[[CiklumOffice builder] mergeFromCodedInputStream:input] build];
}
+ (CiklumOffice*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice*)[[[CiklumOffice builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice_Builder*) builder {
  return [[[CiklumOffice_Builder alloc] init] autorelease];
}
+ (CiklumOffice_Builder*) builderWithPrototype:(CiklumOffice*) prototype {
  return [[CiklumOffice builder] mergeFrom:prototype];
}
- (CiklumOffice_Builder*) builder {
  return [CiklumOffice builder];
}
@end

@interface CiklumOffice_AddressGPB ()
@property (retain) NSString* address;
@property (retain) NSString* country;
@property (retain) NSString* city;
@end

@implementation CiklumOffice_AddressGPB

- (BOOL) hasAddress {
  return !!hasAddress_;
}
- (void) setHasAddress:(BOOL) value {
  hasAddress_ = !!value;
}
@synthesize address;
- (BOOL) hasCountry {
  return !!hasCountry_;
}
- (void) setHasCountry:(BOOL) value {
  hasCountry_ = !!value;
}
@synthesize country;
- (BOOL) hasCity {
  return !!hasCity_;
}
- (void) setHasCity:(BOOL) value {
  hasCity_ = !!value;
}
@synthesize city;
- (void) dealloc {
  self.address = nil;
  self.country = nil;
  self.city = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.address = @"";
    self.country = @"";
    self.city = @"";
  }
  return self;
}
static CiklumOffice_AddressGPB* defaultCiklumOffice_AddressGPBInstance = nil;
+ (void) initialize {
  if (self == [CiklumOffice_AddressGPB class]) {
    defaultCiklumOffice_AddressGPBInstance = [[CiklumOffice_AddressGPB alloc] init];
  }
}
+ (CiklumOffice_AddressGPB*) defaultInstance {
  return defaultCiklumOffice_AddressGPBInstance;
}
- (CiklumOffice_AddressGPB*) defaultInstance {
  return defaultCiklumOffice_AddressGPBInstance;
}
- (BOOL) isInitialized {
  if (!self.hasAddress) {
    return NO;
  }
  if (!self.hasCountry) {
    return NO;
  }
  if (!self.hasCity) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasAddress) {
    [output writeString:1 value:self.address];
  }
  if (self.hasCountry) {
    [output writeString:2 value:self.country];
  }
  if (self.hasCity) {
    [output writeString:3 value:self.city];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasAddress) {
    size += computeStringSize(1, self.address);
  }
  if (self.hasCountry) {
    size += computeStringSize(2, self.country);
  }
  if (self.hasCity) {
    size += computeStringSize(3, self.city);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CiklumOffice_AddressGPB*) parseFromData:(NSData*) data {
  return (CiklumOffice_AddressGPB*)[[[CiklumOffice_AddressGPB builder] mergeFromData:data] build];
}
+ (CiklumOffice_AddressGPB*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice_AddressGPB*)[[[CiklumOffice_AddressGPB builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice_AddressGPB*) parseFromInputStream:(NSInputStream*) input {
  return (CiklumOffice_AddressGPB*)[[[CiklumOffice_AddressGPB builder] mergeFromInputStream:input] build];
}
+ (CiklumOffice_AddressGPB*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice_AddressGPB*)[[[CiklumOffice_AddressGPB builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice_AddressGPB*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CiklumOffice_AddressGPB*)[[[CiklumOffice_AddressGPB builder] mergeFromCodedInputStream:input] build];
}
+ (CiklumOffice_AddressGPB*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice_AddressGPB*)[[[CiklumOffice_AddressGPB builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice_AddressGPB_Builder*) builder {
  return [[[CiklumOffice_AddressGPB_Builder alloc] init] autorelease];
}
+ (CiklumOffice_AddressGPB_Builder*) builderWithPrototype:(CiklumOffice_AddressGPB*) prototype {
  return [[CiklumOffice_AddressGPB builder] mergeFrom:prototype];
}
- (CiklumOffice_AddressGPB_Builder*) builder {
  return [CiklumOffice_AddressGPB builder];
}
@end

@interface CiklumOffice_AddressGPB_Builder()
@property (retain) CiklumOffice_AddressGPB* result;
@end

@implementation CiklumOffice_AddressGPB_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CiklumOffice_AddressGPB alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CiklumOffice_AddressGPB_Builder*) clear {
  self.result = [[[CiklumOffice_AddressGPB alloc] init] autorelease];
  return self;
}
- (CiklumOffice_AddressGPB_Builder*) clone {
  return [CiklumOffice_AddressGPB builderWithPrototype:result];
}
- (CiklumOffice_AddressGPB*) defaultInstance {
  return [CiklumOffice_AddressGPB defaultInstance];
}
- (CiklumOffice_AddressGPB*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CiklumOffice_AddressGPB*) buildPartial {
  CiklumOffice_AddressGPB* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CiklumOffice_AddressGPB_Builder*) mergeFrom:(CiklumOffice_AddressGPB*) other {
  if (other == [CiklumOffice_AddressGPB defaultInstance]) {
    return self;
  }
  if (other.hasAddress) {
    [self setAddress:other.address];
  }
  if (other.hasCountry) {
    [self setCountry:other.country];
  }
  if (other.hasCity) {
    [self setCity:other.city];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CiklumOffice_AddressGPB_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CiklumOffice_AddressGPB_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setAddress:[input readString]];
        break;
      }
      case 18: {
        [self setCountry:[input readString]];
        break;
      }
      case 26: {
        [self setCity:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasAddress {
  return result.hasAddress;
}
- (NSString*) address {
  return result.address;
}
- (CiklumOffice_AddressGPB_Builder*) setAddress:(NSString*) value {
  result.hasAddress = YES;
  result.address = value;
  return self;
}
- (CiklumOffice_AddressGPB_Builder*) clearAddress {
  result.hasAddress = NO;
  result.address = @"";
  return self;
}
- (BOOL) hasCountry {
  return result.hasCountry;
}
- (NSString*) country {
  return result.country;
}
- (CiklumOffice_AddressGPB_Builder*) setCountry:(NSString*) value {
  result.hasCountry = YES;
  result.country = value;
  return self;
}
- (CiklumOffice_AddressGPB_Builder*) clearCountry {
  result.hasCountry = NO;
  result.country = @"";
  return self;
}
- (BOOL) hasCity {
  return result.hasCity;
}
- (NSString*) city {
  return result.city;
}
- (CiklumOffice_AddressGPB_Builder*) setCity:(NSString*) value {
  result.hasCity = YES;
  result.city = value;
  return self;
}
- (CiklumOffice_AddressGPB_Builder*) clearCity {
  result.hasCity = NO;
  result.city = @"";
  return self;
}
@end

@interface CiklumOffice_EmployeeGPB ()
@property (retain) NSString* name;
@property CiklumOffice_EmployeeGPB_EmployeeType type;
@property (retain) CiklumOffice_AddressGPB* address;
@property (retain) NSData* photo;
@end

@implementation CiklumOffice_EmployeeGPB

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value {
  hasType_ = !!value;
}
@synthesize type;
- (BOOL) hasAddress {
  return !!hasAddress_;
}
- (void) setHasAddress:(BOOL) value {
  hasAddress_ = !!value;
}
@synthesize address;
- (BOOL) hasPhoto {
  return !!hasPhoto_;
}
- (void) setHasPhoto:(BOOL) value {
  hasPhoto_ = !!value;
}
@synthesize photo;
- (void) dealloc {
  self.name = nil;
  self.address = nil;
  self.photo = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.name = @"";
    self.type = CiklumOffice_EmployeeGPB_EmployeeTypeIOsdev;
    self.address = [CiklumOffice_AddressGPB defaultInstance];
    self.photo = [NSData data];
  }
  return self;
}
static CiklumOffice_EmployeeGPB* defaultCiklumOffice_EmployeeGPBInstance = nil;
+ (void) initialize {
  if (self == [CiklumOffice_EmployeeGPB class]) {
    defaultCiklumOffice_EmployeeGPBInstance = [[CiklumOffice_EmployeeGPB alloc] init];
  }
}
+ (CiklumOffice_EmployeeGPB*) defaultInstance {
  return defaultCiklumOffice_EmployeeGPBInstance;
}
- (CiklumOffice_EmployeeGPB*) defaultInstance {
  return defaultCiklumOffice_EmployeeGPBInstance;
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasType) {
    return NO;
  }
  if (self.hasAddress) {
    if (!self.address.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasType) {
    [output writeEnum:2 value:self.type];
  }
  if (self.hasAddress) {
    [output writeMessage:3 value:self.address];
  }
  if (self.hasPhoto) {
    [output writeData:4 value:self.photo];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasName) {
    size += computeStringSize(1, self.name);
  }
  if (self.hasType) {
    size += computeEnumSize(2, self.type);
  }
  if (self.hasAddress) {
    size += computeMessageSize(3, self.address);
  }
  if (self.hasPhoto) {
    size += computeDataSize(4, self.photo);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (CiklumOffice_EmployeeGPB*) parseFromData:(NSData*) data {
  return (CiklumOffice_EmployeeGPB*)[[[CiklumOffice_EmployeeGPB builder] mergeFromData:data] build];
}
+ (CiklumOffice_EmployeeGPB*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice_EmployeeGPB*)[[[CiklumOffice_EmployeeGPB builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice_EmployeeGPB*) parseFromInputStream:(NSInputStream*) input {
  return (CiklumOffice_EmployeeGPB*)[[[CiklumOffice_EmployeeGPB builder] mergeFromInputStream:input] build];
}
+ (CiklumOffice_EmployeeGPB*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice_EmployeeGPB*)[[[CiklumOffice_EmployeeGPB builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice_EmployeeGPB*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CiklumOffice_EmployeeGPB*)[[[CiklumOffice_EmployeeGPB builder] mergeFromCodedInputStream:input] build];
}
+ (CiklumOffice_EmployeeGPB*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CiklumOffice_EmployeeGPB*)[[[CiklumOffice_EmployeeGPB builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CiklumOffice_EmployeeGPB_Builder*) builder {
  return [[[CiklumOffice_EmployeeGPB_Builder alloc] init] autorelease];
}
+ (CiklumOffice_EmployeeGPB_Builder*) builderWithPrototype:(CiklumOffice_EmployeeGPB*) prototype {
  return [[CiklumOffice_EmployeeGPB builder] mergeFrom:prototype];
}
- (CiklumOffice_EmployeeGPB_Builder*) builder {
  return [CiklumOffice_EmployeeGPB builder];
}
@end

BOOL CiklumOffice_EmployeeGPB_EmployeeTypeIsValidValue(CiklumOffice_EmployeeGPB_EmployeeType value) {
  switch (value) {
    case CiklumOffice_EmployeeGPB_EmployeeTypeIOsdev:
    case CiklumOffice_EmployeeGPB_EmployeeTypeAndroidDev:
    case CiklumOffice_EmployeeGPB_EmployeeTypeWp7Dev:
    case CiklumOffice_EmployeeGPB_EmployeeTypeManager:
      return YES;
    default:
      return NO;
  }
}
@interface CiklumOffice_EmployeeGPB_Builder()
@property (retain) CiklumOffice_EmployeeGPB* result;
@end

@implementation CiklumOffice_EmployeeGPB_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CiklumOffice_EmployeeGPB alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CiklumOffice_EmployeeGPB_Builder*) clear {
  self.result = [[[CiklumOffice_EmployeeGPB alloc] init] autorelease];
  return self;
}
- (CiklumOffice_EmployeeGPB_Builder*) clone {
  return [CiklumOffice_EmployeeGPB builderWithPrototype:result];
}
- (CiklumOffice_EmployeeGPB*) defaultInstance {
  return [CiklumOffice_EmployeeGPB defaultInstance];
}
- (CiklumOffice_EmployeeGPB*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CiklumOffice_EmployeeGPB*) buildPartial {
  CiklumOffice_EmployeeGPB* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CiklumOffice_EmployeeGPB_Builder*) mergeFrom:(CiklumOffice_EmployeeGPB*) other {
  if (other == [CiklumOffice_EmployeeGPB defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasAddress) {
    [self mergeAddress:other.address];
  }
  if (other.hasPhoto) {
    [self setPhoto:other.photo];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CiklumOffice_EmployeeGPB_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CiklumOffice_EmployeeGPB_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 16: {
        int32_t value = [input readEnum];
        if (CiklumOffice_EmployeeGPB_EmployeeTypeIsValidValue(value)) {
          [self setType:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
      case 26: {
        CiklumOffice_AddressGPB_Builder* subBuilder = [CiklumOffice_AddressGPB builder];
        if (self.hasAddress) {
          [subBuilder mergeFrom:self.address];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setAddress:[subBuilder buildPartial]];
        break;
      }
      case 34: {
        [self setPhoto:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (CiklumOffice_EmployeeGPB_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (CiklumOffice_EmployeeGPB_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (CiklumOffice_EmployeeGPB_EmployeeType) type {
  return result.type;
}
- (CiklumOffice_EmployeeGPB_Builder*) setType:(CiklumOffice_EmployeeGPB_EmployeeType) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (CiklumOffice_EmployeeGPB_Builder*) clearType {
  result.hasType = NO;
  result.type = CiklumOffice_EmployeeGPB_EmployeeTypeIOsdev;
  return self;
}
- (BOOL) hasAddress {
  return result.hasAddress;
}
- (CiklumOffice_AddressGPB*) address {
  return result.address;
}
- (CiklumOffice_EmployeeGPB_Builder*) setAddress:(CiklumOffice_AddressGPB*) value {
  result.hasAddress = YES;
  result.address = value;
  return self;
}
- (CiklumOffice_EmployeeGPB_Builder*) setAddressBuilder:(CiklumOffice_AddressGPB_Builder*) builderForValue {
  return [self setAddress:[builderForValue build]];
}
- (CiklumOffice_EmployeeGPB_Builder*) mergeAddress:(CiklumOffice_AddressGPB*) value {
  if (result.hasAddress &&
      result.address != [CiklumOffice_AddressGPB defaultInstance]) {
    result.address =
      [[[CiklumOffice_AddressGPB builderWithPrototype:result.address] mergeFrom:value] buildPartial];
  } else {
    result.address = value;
  }
  result.hasAddress = YES;
  return self;
}
- (CiklumOffice_EmployeeGPB_Builder*) clearAddress {
  result.hasAddress = NO;
  result.address = [CiklumOffice_AddressGPB defaultInstance];
  return self;
}
- (BOOL) hasPhoto {
  return result.hasPhoto;
}
- (NSData*) photo {
  return result.photo;
}
- (CiklumOffice_EmployeeGPB_Builder*) setPhoto:(NSData*) value {
  result.hasPhoto = YES;
  result.photo = value;
  return self;
}
- (CiklumOffice_EmployeeGPB_Builder*) clearPhoto {
  result.hasPhoto = NO;
  result.photo = [NSData data];
  return self;
}
@end

@interface CiklumOffice_Builder()
@property (retain) CiklumOffice* result;
@end

@implementation CiklumOffice_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CiklumOffice alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CiklumOffice_Builder*) clear {
  self.result = [[[CiklumOffice alloc] init] autorelease];
  return self;
}
- (CiklumOffice_Builder*) clone {
  return [CiklumOffice builderWithPrototype:result];
}
- (CiklumOffice*) defaultInstance {
  return [CiklumOffice defaultInstance];
}
- (CiklumOffice*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CiklumOffice*) buildPartial {
  CiklumOffice* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CiklumOffice_Builder*) mergeFrom:(CiklumOffice*) other {
  if (other == [CiklumOffice defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasAddress) {
    [self mergeAddress:other.address];
  }
  if (other.mutableEmployeesList.count > 0) {
    if (result.mutableEmployeesList == nil) {
      result.mutableEmployeesList = [NSMutableArray array];
    }
    [result.mutableEmployeesList addObjectsFromArray:other.mutableEmployeesList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CiklumOffice_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CiklumOffice_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 18: {
        CiklumOffice_AddressGPB_Builder* subBuilder = [CiklumOffice_AddressGPB builder];
        if (self.hasAddress) {
          [subBuilder mergeFrom:self.address];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setAddress:[subBuilder buildPartial]];
        break;
      }
      case 26: {
        CiklumOffice_EmployeeGPB_Builder* subBuilder = [CiklumOffice_EmployeeGPB builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addEmployees:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (CiklumOffice_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (CiklumOffice_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasAddress {
  return result.hasAddress;
}
- (CiklumOffice_AddressGPB*) address {
  return result.address;
}
- (CiklumOffice_Builder*) setAddress:(CiklumOffice_AddressGPB*) value {
  result.hasAddress = YES;
  result.address = value;
  return self;
}
- (CiklumOffice_Builder*) setAddressBuilder:(CiklumOffice_AddressGPB_Builder*) builderForValue {
  return [self setAddress:[builderForValue build]];
}
- (CiklumOffice_Builder*) mergeAddress:(CiklumOffice_AddressGPB*) value {
  if (result.hasAddress &&
      result.address != [CiklumOffice_AddressGPB defaultInstance]) {
    result.address =
      [[[CiklumOffice_AddressGPB builderWithPrototype:result.address] mergeFrom:value] buildPartial];
  } else {
    result.address = value;
  }
  result.hasAddress = YES;
  return self;
}
- (CiklumOffice_Builder*) clearAddress {
  result.hasAddress = NO;
  result.address = [CiklumOffice_AddressGPB defaultInstance];
  return self;
}
- (NSArray*) employeesList {
  if (result.mutableEmployeesList == nil) { return [NSArray array]; }
  return result.mutableEmployeesList;
}
- (CiklumOffice_EmployeeGPB*) employeesAtIndex:(int32_t) index {
  return [result employeesAtIndex:index];
}
- (CiklumOffice_Builder*) replaceEmployeesAtIndex:(int32_t) index with:(CiklumOffice_EmployeeGPB*) value {
  [result.mutableEmployeesList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (CiklumOffice_Builder*) addAllEmployees:(NSArray*) values {
  if (result.mutableEmployeesList == nil) {
    result.mutableEmployeesList = [NSMutableArray array];
  }
  [result.mutableEmployeesList addObjectsFromArray:values];
  return self;
}
- (CiklumOffice_Builder*) clearEmployeesList {
  result.mutableEmployeesList = nil;
  return self;
}
- (CiklumOffice_Builder*) addEmployees:(CiklumOffice_EmployeeGPB*) value {
  if (result.mutableEmployeesList == nil) {
    result.mutableEmployeesList = [NSMutableArray array];
  }
  [result.mutableEmployeesList addObject:value];
  return self;
}
@end

