// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Shop.pb.h"

@implementation ShopRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ShopRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Product ()
@property (retain) NSString* name;
@property int32_t id;
@property int32_t price;
@property BOOL starred;
@property Product_OrderStatus status;
@property (retain) NSMutableArray* mutableReviewsList;
@end

@implementation Product

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value {
  hasId_ = !!value;
}
@synthesize id;
- (BOOL) hasPrice {
  return !!hasPrice_;
}
- (void) setHasPrice:(BOOL) value {
  hasPrice_ = !!value;
}
@synthesize price;
- (BOOL) hasStarred {
  return !!hasStarred_;
}
- (void) setHasStarred:(BOOL) value {
  hasStarred_ = !!value;
}
- (BOOL) starred {
  return !!starred_;
}
- (void) setStarred:(BOOL) value {
  starred_ = !!value;
}
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
@synthesize mutableReviewsList;
- (void) dealloc {
  self.name = nil;
  self.mutableReviewsList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.name = @"";
    self.id = 0;
    self.price = 0;
    self.starred = NO;
    self.status = Product_OrderStatusOrdered;
  }
  return self;
}
static Product* defaultProductInstance = nil;
+ (void) initialize {
  if (self == [Product class]) {
    defaultProductInstance = [[Product alloc] init];
  }
}
+ (Product*) defaultInstance {
  return defaultProductInstance;
}
- (Product*) defaultInstance {
  return defaultProductInstance;
}
- (NSArray*) reviewsList {
  return mutableReviewsList;
}
- (Product_ProductReview*) reviewsAtIndex:(int32_t) index {
  id value = [mutableReviewsList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  if (!self.hasId) {
    return NO;
  }
  for (Product_ProductReview* element in self.reviewsList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasId) {
    [output writeInt32:2 value:self.id];
  }
  if (self.hasPrice) {
    [output writeInt32:3 value:self.price];
  }
  if (self.hasStarred) {
    [output writeBool:4 value:self.starred];
  }
  if (self.hasStatus) {
    [output writeEnum:5 value:self.status];
  }
  for (Product_ProductReview* element in self.reviewsList) {
    [output writeMessage:6 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasName) {
    size += computeStringSize(1, self.name);
  }
  if (self.hasId) {
    size += computeInt32Size(2, self.id);
  }
  if (self.hasPrice) {
    size += computeInt32Size(3, self.price);
  }
  if (self.hasStarred) {
    size += computeBoolSize(4, self.starred);
  }
  if (self.hasStatus) {
    size += computeEnumSize(5, self.status);
  }
  for (Product_ProductReview* element in self.reviewsList) {
    size += computeMessageSize(6, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Product*) parseFromData:(NSData*) data {
  return (Product*)[[[Product builder] mergeFromData:data] build];
}
+ (Product*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product*)[[[Product builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Product*) parseFromInputStream:(NSInputStream*) input {
  return (Product*)[[[Product builder] mergeFromInputStream:input] build];
}
+ (Product*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product*)[[[Product builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Product*)[[[Product builder] mergeFromCodedInputStream:input] build];
}
+ (Product*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product*)[[[Product builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Product_Builder*) builder {
  return [[[Product_Builder alloc] init] autorelease];
}
+ (Product_Builder*) builderWithPrototype:(Product*) prototype {
  return [[Product builder] mergeFrom:prototype];
}
- (Product_Builder*) builder {
  return [Product builder];
}
@end

BOOL Product_OrderStatusIsValidValue(Product_OrderStatus value) {
  switch (value) {
    case Product_OrderStatusOrdered:
    case Product_OrderStatusShipped:
    case Product_OrderStatusIdle:
      return YES;
    default:
      return NO;
  }
}
@interface Product_ProductReview ()
@property int32_t id;
@property (retain) NSString* reviewer;
@property (retain) NSString* review;
@property int32_t rating;
@end

@implementation Product_ProductReview

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value {
  hasId_ = !!value;
}
@synthesize id;
- (BOOL) hasReviewer {
  return !!hasReviewer_;
}
- (void) setHasReviewer:(BOOL) value {
  hasReviewer_ = !!value;
}
@synthesize reviewer;
- (BOOL) hasReview {
  return !!hasReview_;
}
- (void) setHasReview:(BOOL) value {
  hasReview_ = !!value;
}
@synthesize review;
- (BOOL) hasRating {
  return !!hasRating_;
}
- (void) setHasRating:(BOOL) value {
  hasRating_ = !!value;
}
@synthesize rating;
- (void) dealloc {
  self.reviewer = nil;
  self.review = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.reviewer = @"";
    self.review = @"";
    self.rating = 0;
  }
  return self;
}
static Product_ProductReview* defaultProduct_ProductReviewInstance = nil;
+ (void) initialize {
  if (self == [Product_ProductReview class]) {
    defaultProduct_ProductReviewInstance = [[Product_ProductReview alloc] init];
  }
}
+ (Product_ProductReview*) defaultInstance {
  return defaultProduct_ProductReviewInstance;
}
- (Product_ProductReview*) defaultInstance {
  return defaultProduct_ProductReviewInstance;
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasRating) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt32:1 value:self.id];
  }
  if (self.hasReviewer) {
    [output writeString:2 value:self.reviewer];
  }
  if (self.hasReview) {
    [output writeString:3 value:self.review];
  }
  if (self.hasRating) {
    [output writeInt32:4 value:self.rating];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeInt32Size(1, self.id);
  }
  if (self.hasReviewer) {
    size += computeStringSize(2, self.reviewer);
  }
  if (self.hasReview) {
    size += computeStringSize(3, self.review);
  }
  if (self.hasRating) {
    size += computeInt32Size(4, self.rating);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Product_ProductReview*) parseFromData:(NSData*) data {
  return (Product_ProductReview*)[[[Product_ProductReview builder] mergeFromData:data] build];
}
+ (Product_ProductReview*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product_ProductReview*)[[[Product_ProductReview builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Product_ProductReview*) parseFromInputStream:(NSInputStream*) input {
  return (Product_ProductReview*)[[[Product_ProductReview builder] mergeFromInputStream:input] build];
}
+ (Product_ProductReview*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product_ProductReview*)[[[Product_ProductReview builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Product_ProductReview*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Product_ProductReview*)[[[Product_ProductReview builder] mergeFromCodedInputStream:input] build];
}
+ (Product_ProductReview*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Product_ProductReview*)[[[Product_ProductReview builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Product_ProductReview_Builder*) builder {
  return [[[Product_ProductReview_Builder alloc] init] autorelease];
}
+ (Product_ProductReview_Builder*) builderWithPrototype:(Product_ProductReview*) prototype {
  return [[Product_ProductReview builder] mergeFrom:prototype];
}
- (Product_ProductReview_Builder*) builder {
  return [Product_ProductReview builder];
}
@end

@interface Product_ProductReview_Builder()
@property (retain) Product_ProductReview* result;
@end

@implementation Product_ProductReview_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Product_ProductReview alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Product_ProductReview_Builder*) clear {
  self.result = [[[Product_ProductReview alloc] init] autorelease];
  return self;
}
- (Product_ProductReview_Builder*) clone {
  return [Product_ProductReview builderWithPrototype:result];
}
- (Product_ProductReview*) defaultInstance {
  return [Product_ProductReview defaultInstance];
}
- (Product_ProductReview*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Product_ProductReview*) buildPartial {
  Product_ProductReview* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Product_ProductReview_Builder*) mergeFrom:(Product_ProductReview*) other {
  if (other == [Product_ProductReview defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasReviewer) {
    [self setReviewer:other.reviewer];
  }
  if (other.hasReview) {
    [self setReview:other.review];
  }
  if (other.hasRating) {
    [self setRating:other.rating];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Product_ProductReview_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Product_ProductReview_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt32]];
        break;
      }
      case 18: {
        [self setReviewer:[input readString]];
        break;
      }
      case 26: {
        [self setReview:[input readString]];
        break;
      }
      case 32: {
        [self setRating:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (int32_t) id {
  return result.id;
}
- (Product_ProductReview_Builder*) setId:(int32_t) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (Product_ProductReview_Builder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasReviewer {
  return result.hasReviewer;
}
- (NSString*) reviewer {
  return result.reviewer;
}
- (Product_ProductReview_Builder*) setReviewer:(NSString*) value {
  result.hasReviewer = YES;
  result.reviewer = value;
  return self;
}
- (Product_ProductReview_Builder*) clearReviewer {
  result.hasReviewer = NO;
  result.reviewer = @"";
  return self;
}
- (BOOL) hasReview {
  return result.hasReview;
}
- (NSString*) review {
  return result.review;
}
- (Product_ProductReview_Builder*) setReview:(NSString*) value {
  result.hasReview = YES;
  result.review = value;
  return self;
}
- (Product_ProductReview_Builder*) clearReview {
  result.hasReview = NO;
  result.review = @"";
  return self;
}
- (BOOL) hasRating {
  return result.hasRating;
}
- (int32_t) rating {
  return result.rating;
}
- (Product_ProductReview_Builder*) setRating:(int32_t) value {
  result.hasRating = YES;
  result.rating = value;
  return self;
}
- (Product_ProductReview_Builder*) clearRating {
  result.hasRating = NO;
  result.rating = 0;
  return self;
}
@end

@interface Product_Builder()
@property (retain) Product* result;
@end

@implementation Product_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Product alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Product_Builder*) clear {
  self.result = [[[Product alloc] init] autorelease];
  return self;
}
- (Product_Builder*) clone {
  return [Product builderWithPrototype:result];
}
- (Product*) defaultInstance {
  return [Product defaultInstance];
}
- (Product*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Product*) buildPartial {
  Product* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Product_Builder*) mergeFrom:(Product*) other {
  if (other == [Product defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasPrice) {
    [self setPrice:other.price];
  }
  if (other.hasStarred) {
    [self setStarred:other.starred];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.mutableReviewsList.count > 0) {
    if (result.mutableReviewsList == nil) {
      result.mutableReviewsList = [NSMutableArray array];
    }
    [result.mutableReviewsList addObjectsFromArray:other.mutableReviewsList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Product_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 16: {
        [self setId:[input readInt32]];
        break;
      }
      case 24: {
        [self setPrice:[input readInt32]];
        break;
      }
      case 32: {
        [self setStarred:[input readBool]];
        break;
      }
      case 40: {
        int32_t value = [input readEnum];
        if (Product_OrderStatusIsValidValue(value)) {
          [self setStatus:value];
        } else {
          [unknownFields mergeVarintField:5 value:value];
        }
        break;
      }
      case 50: {
        Product_ProductReview_Builder* subBuilder = [Product_ProductReview builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addReviews:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (Product_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (Product_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasId {
  return result.hasId;
}
- (int32_t) id {
  return result.id;
}
- (Product_Builder*) setId:(int32_t) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (Product_Builder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasPrice {
  return result.hasPrice;
}
- (int32_t) price {
  return result.price;
}
- (Product_Builder*) setPrice:(int32_t) value {
  result.hasPrice = YES;
  result.price = value;
  return self;
}
- (Product_Builder*) clearPrice {
  result.hasPrice = NO;
  result.price = 0;
  return self;
}
- (BOOL) hasStarred {
  return result.hasStarred;
}
- (BOOL) starred {
  return result.starred;
}
- (Product_Builder*) setStarred:(BOOL) value {
  result.hasStarred = YES;
  result.starred = value;
  return self;
}
- (Product_Builder*) clearStarred {
  result.hasStarred = NO;
  result.starred = NO;
  return self;
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (Product_OrderStatus) status {
  return result.status;
}
- (Product_Builder*) setStatus:(Product_OrderStatus) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (Product_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = Product_OrderStatusOrdered;
  return self;
}
- (NSArray*) reviewsList {
  if (result.mutableReviewsList == nil) { return [NSArray array]; }
  return result.mutableReviewsList;
}
- (Product_ProductReview*) reviewsAtIndex:(int32_t) index {
  return [result reviewsAtIndex:index];
}
- (Product_Builder*) replaceReviewsAtIndex:(int32_t) index with:(Product_ProductReview*) value {
  [result.mutableReviewsList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (Product_Builder*) addAllReviews:(NSArray*) values {
  if (result.mutableReviewsList == nil) {
    result.mutableReviewsList = [NSMutableArray array];
  }
  [result.mutableReviewsList addObjectsFromArray:values];
  return self;
}
- (Product_Builder*) clearReviewsList {
  result.mutableReviewsList = nil;
  return self;
}
- (Product_Builder*) addReviews:(Product_ProductReview*) value {
  if (result.mutableReviewsList == nil) {
    result.mutableReviewsList = [NSMutableArray array];
  }
  [result.mutableReviewsList addObject:value];
  return self;
}
@end

